### ISSUE TITLE
not able to make a submission with debug set to "false"

### ISSUE THREAD

**Issue by VedikaSrivastava** [minerllabs/basalt_2022_competition_submission_template#5]
i edited the aicrowd.json file and set default to false. and followed the same steps to make a submission as mentioned but a different submission number. However its not pushing the changed file.

Is anyone else also facing the problem? Can anyone pls help me.

**Comment by Miffyli** [comment]
Hey! Can you share link to the submission repository. Committing the change and pushing it should definitely change it.

**Comment by VedikaSrivastava** [comment]
> Hey! Can you share link to the submission repository. Committing the change and pushing it should definitely change it.

are u referring to this link?

https://gitlab.aicrowd.com/vedikas/basalt_2022_competition_submission_template/-/issues

**Comment by VedikaSrivastava** [comment]
> > Hey! Can you share link to the submission repository. Committing the change and pushing it should definitely change it.
> 
> are u referring to this link?
> 
> https://gitlab.aicrowd.com/vedikas/basalt_2022_competition_submission_template/-/issues

I figured out the issue here, i wasn't sending my changes to a new private repo.
